### ISSUE TITLE
son-package error messages

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/son-cli#114]
When you try to package a project, and your VNFDs are not placed in subfolders (one subfolder per VNFD) the packaging tool fails with an error that does not provide much insights.

It happens e.g. if you have:

```
sources/
    vnf/
        vnfd1.yml
        vnfd2.yml
```

instead of:

```
source/
     vnf/
        vnf1/
           vnfd1.yml
         vnf2/
           vnfd2.yml
```

For me as a user of the tool it was confusing to find the reason for this error when looking at the following output:

```
2016-08-30 08:55:55 dev-vm son.package.package[6139] ERROR Unable to solve all dependencies required by the service descriptor.
2016-08-30 08:55:55 dev-vm son.package.package[6139] ERROR Failed to package function descriptors
2016-08-30 08:55:55 dev-vm son.package.package[6139] INFO package_pcs executed in 0.506 sec
2016-08-30 08:55:55 dev-vm son.package.package[6139] INFO Create Package Resolver Section
2016-08-30 08:55:55 dev-vm son.package.package[6139] INFO package_prs executed in 0.000 sec
2016-08-30 08:55:55 dev-vm son.package.package[6139] INFO Create Package Dependencies Section
2016-08-30 08:55:55 dev-vm son.package.package[6139] INFO package_pds executed in 0.000 sec
2016-08-30 08:55:55 dev-vm son.package.package[6139] INFO Create Artifact Dependencies Section
2016-08-30 08:55:55 dev-vm son.package.package[6139] INFO package_ads executed in 0.000 sec
2016-08-30 08:55:55 dev-vm son.package.package[6139] INFO Create General Description section
2016-08-30 08:55:55 dev-vm son.package.package[6139] INFO package_gds executed in 0.000 sec
Traceback (most recent call last):
  File "/usr/local/bin/son-package", line 9, in <module>
    load_entry_point('sonata-cli', 'console_scripts', 'son-package')()
  File "/home/manuel/son-cli/src/son/package/package.py", line 877, in main
    pck = Packager(workspace, project, dst_path=args.destination)
  File "/home/manuel/son-cli/src/son/package/package.py", line 97, in __init__
    self.package_descriptor = self._project
  File "/home/manuel/son-cli/src/son/package/package.py", line 158, in package_descriptor
    self._package_descriptor.update(package_content)
TypeError: 'bool' object is not iterable


```

- Why do we need the VNFDs to be placed in separated subfolders? 
- The tool might detect this and say that it didn't find the VNFDs

**Comment by lconceicao** [comment]
The decision of putting each VNF inside a separate folder was intentional as some VNFs may have artifacts associated with them (e.g. docker files) which would be placed inside the same folder.
I'm going to reproduce the error and add a more intuitive error.

**Comment by mpeuster** [comment]
@lconceicao Yes, the folder structure makes sense. A nice error will solve the problem. Maybe we can also think about a feature which _initializes_ a project: Create folder structure, minimal VNFDs etc. to simplify this process for our users.

**Comment by lconceicao** [comment]
The `son-workspace --project .." command already creates a project structure, containing a sample service descriptor and function descritor. Or are you referring to something more complex?

**Comment by mpeuster** [comment]
@lconceicao Ah. No no this is exactly what I am talking about 👍

**Comment by lconceicao** [comment]
@mpeuster Can you confirm that the problem is solved?

**Comment by mpeuster** [comment]
Confirmed! Works fine now 👍 Thanks!

Output:
```
2016-08-30 16:02:32 dev-vm son.package.package[7538] INFO package_gds executed in 0.000 sec
2016-08-30 16:02:32 dev-vm son.package.package[7538] ERROR Failed to package Package Content Section. Could not find a network service and/or its referenced function descriptors
2016-08-30 16:02:32 dev-vm son.package.package[7538] CRITICAL Missing package descriptor. Failed to generate package.
```

Close.
