### ISSUE TITLE
son-cli installation

### ISSUE THREAD

**Issue by tsoenen** [sonata-nfv/son-cli#182]
Hi all,

When following the installation guide (on a clean ubuntu 16.04), I get the following when running bin/buildout

```
An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/tsoenen/sonata/sdk/son-cli/eggs/zc.buildout-2.9.3-py3.5.egg/zc/buildout/buildout.py", line 2123, in main
    getattr(buildout, command)(args)
  File "/home/tsoenen/sonata/sdk/son-cli/eggs/zc.buildout-2.9.3-py3.5.egg/zc/buildout/buildout.py", line 796, in install
    installed_files = self[part]._call(recipe.install)
  File "/home/tsoenen/sonata/sdk/son-cli/eggs/zc.buildout-2.9.3-py3.5.egg/zc/buildout/buildout.py", line 1553, in _call
    return f()
  File "/home/tsoenen/sonata/sdk/son-cli/eggs/zc.recipe.egg-2.0.3-py3.5.egg/zc/recipe/egg/egg.py", line 126, in install
    reqs, ws = self.working_set()
  File "/home/tsoenen/sonata/sdk/son-cli/eggs/zc.recipe.egg-2.0.3-py3.5.egg/zc/recipe/egg/egg.py", line 84, in working_set
    allow_hosts=self.allow_hosts)
  File "/home/tsoenen/sonata/sdk/son-cli/eggs/zc.buildout-2.9.3-py3.5.egg/zc/buildout/easy_install.py", line 913, in install
    return installer.install(specs, working_set)
  File "/home/tsoenen/sonata/sdk/son-cli/eggs/zc.buildout-2.9.3-py3.5.egg/zc/buildout/easy_install.py", line 714, in install
    for dist in self._get_dist(req, ws):
  File "/home/tsoenen/sonata/sdk/son-cli/eggs/zc.buildout-2.9.3-py3.5.egg/zc/buildout/easy_install.py", line 563, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "/home/tsoenen/sonata/sdk/son-cli/eggs/zc.buildout-2.9.3-py3.5.egg/zc/buildout/easy_install.py", line 1699, in _move_to_eggs_dir_and_compile
    [tmp_loc] = glob.glob(os.path.join(tmp_dest, '*'))
ValueError: not enough values to unpack (expected 1, got 0)
```

**Comment by mpeuster** [comment]
Hi Thomas,
I also noticed these problems when doing the `bin/buildout` step.

I typically simply use `python setup.py install` to install the CLI which works much better for me.

**Comment by lconceicao** [comment]
I also noticed errors related with scipy and numpy packages. I have to pip install these manually and then do the `bin/buildout` step.

**Comment by tsoenen** [comment]
Ok, I went with the fix that @mpeuster suggested. Next, if I try to use son-access or son-package, I get the following:

```
Traceback (most recent call last):
  File "/usr/local/bin/son-access", line 9, in <module>
    load_entry_point('sonata-cli==0.9', 'console_scripts', 'son-access')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/sonata_cli-0.9-py2.7.egg/son/access/access.py", line 66, in <module>
    from son.workspace.workspace import Workspace
  File "/usr/local/lib/python2.7/dist-packages/sonata_cli-0.9-py2.7.egg/son/workspace/workspace.py", line 366
    .format(ws_root), file=sys.stderr)
                          ^
SyntaxError: invalid syntax

```

**Comment by lconceicao** [comment]
Are you using python 3?

**Comment by mpeuster** [comment]
Yeah, maybe I should have mentioned: I always use a fresh Python3 venv for it.

**Comment by tsoenen** [comment]
I'm doing the following:

```
source /usr/local/bin/virtualenvwrapper.sh
mkvirtualenv -p /usr/bin/python3.4 cli
cd cli/
git clone http://github.com/sonata-nfv/son-cli.git
cd on-cli/
python3 bootstrap.py
python3 setup.py install
```

This is giving an error on the last command. Which step am I doing wrong?

**Comment by lconceicao** [comment]
I cannot reproduce you error following those steps, but I am using python3.5. Nonetheless an error related with numpy occurs which is solved by installing manually scipy and then re-running the install command.

**Comment by tsoenen** [comment]
Have you tried it in a clean OS?

What do you run to install scipy?

**Comment by lconceicao** [comment]
No, just a clean venv.
To manually install scipy just run `pip install scipy`

**Comment by lconceicao** [comment]
Perhaps is the error is due to a missing dependency. Make sure you install all these packages system-wide, using apt:
`software-properties-common apt-transport-https ca-certificates wget libffi-dev libssl-dev tcpdump gfortran libopenblas-dev liblapack-dev python3-dev libyaml-dev curl python3.pip python3-pycparser`

**Comment by lconceicao** [comment]
@tsoenen do you still have this issue?
